version: '3'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-chatting}
      MYSQL_USER: ${MYSQL_USER:-tester}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-test1234}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  db-redis-cache:
    image: redis:6.2.7-alpine
    container_name: db-redis-cache
    command: redis-server --port 6379
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"

volumes:
  db_data: